version: "3.3"

services: 
        nginx:
                image: nginx:latest
                ports: 
                        - "83:83"
                        - "84:84"
                volumes:
                        - "./hosts:/etc/nginx/conf.d"
                networks:
                        projects_net:
                                aliases:
                                        - project-proxy
networks:
  projects_net:
          external:
                  name: custom-network
